### ISSUE TITLE
Trying to implement this in a Fragment with no success ...

### ISSUE THREAD

**Issue by nuny3010** [mjmotani/NestedRecyclerView-Master#2]
Hi 
How can i use this in fragment?
Fragment has two override methods: OnCreateView and OnCreate..
Where should i use the ButterKnife?
In addition, there is no etContentView(this) for fragment..

I tried the below, with no success, please help:
`public class FragmentPractice extends Fragment {

  
    View view;

    @BindView(R.id.rvVertical)
    RecyclerView rvVertical;

    @BindView(R.id.toolbar)
    Toolbar toolbar;
    ArrayList<VerticalModel> mArrayList = new ArrayList<>();
    VerticalRecyclerViewAdapter mAdapter;

    public FragmentPractice() {
    }

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        view=inflater.inflate(R.layout.practice_fragment, container, false);

        rvVertical = (RecyclerView) view.findViewById(R.id.rvVertical);

        return view;
    }

    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        //setContentView(this);
        ButterKnife.bind(view);

        toolbar.setTitle(R.string.app_name);
        //setSupportActionBar(toolbar);

        rvVertical.setLayoutManager(new LinearLayoutManager(getActivity(), LinearLayoutManager.VERTICAL, false));
        mAdapter = new VerticalRecyclerViewAdapter(getContext(), mArrayList);
        rvVertical.setAdapter(mAdapter);

        setDataOnVerticalRecyclerView();
  
    }

    private void setDataOnVerticalRecyclerView() {
        for (int i = 1; i <= 5; i++) {

            VerticalModel mVerticalModel = new VerticalModel();

            mVerticalModel.setTitle("Title " + i);

            ArrayList<HorizontalModel> arrayList = new ArrayList<>();

            for (int j = 0; j <= 5; j++) {
                HorizontalModel mHorizontalModel = new HorizontalModel();
                mHorizontalModel.setDescription("Description : " + j);
                mHorizontalModel.setName("Name : " + j);
                arrayList.add(mHorizontalModel);
            }

            mVerticalModel.setArrayList(arrayList);

            mArrayList.add(mVerticalModel);

        }
        mAdapter.notifyDataSetChanged();
    }

    private void setTextViewTitle (TextView textView, String title){
        textView.setText(title);
        textView.setTextColor(Color.rgb(	36, 59, 85));
        textView.setTextSize(18f);
        textView.setTypeface(Typeface.DEFAULT_BOLD);
    }
}`

**Comment by malikmotani** [comment]
As you are using this in the fragment you need to use rvVertical with view reference like this way

```
rvVertical.setLayoutManager(new LinearLayoutManager(getActivity(), LinearLayoutManager.VERTICAL, false));
    mAdapter = new VerticalRecyclerViewAdapter(getContext(), mArrayList);
    rvVertical.setAdapter(mAdapter);
```

**Comment by nuny3010** [comment]
Hi Maddy 
Thank you very much for your reply.
Unfortunately it's still not work...
Done under the OnCreatView:
`
public class FragmentPractice extends Fragment {
    View view;
    @BindView(R.id.rvVertical)
    RecyclerView rvVertical;

    @BindView(R.id.toolbar)
    Toolbar toolbar;
    ArrayList<VerticalModel> mArrayList = new ArrayList<>();
    VerticalRecyclerViewAdapter mAdapter;

    public FragmentPractice() {
    }

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        view=inflater.inflate(R.layout.practice_fragment, container, false);

        rvVertical = (RecyclerView) view.findViewById(R.id.rvVertical);
        rvVertical.setLayoutManager(new LinearLayoutManager(getActivity(), LinearLayoutManager.VERTICAL, false));
        mAdapter = new VerticalRecyclerViewAdapter(getContext(), mArrayList);
        rvVertical.setAdapter(mAdapter);

        return view;
    }

    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        setDataOnVerticalRecyclerView();

        //setContentView(this);
        ButterKnife.bind(view);

        toolbar.setTitle(R.string.app_name);
        //setSupportActionBar(toolbar);

    }

    private void setDataOnVerticalRecyclerView() {
        for (int i = 1; i <= 5; i++) {

            VerticalModel mVerticalModel = new VerticalModel();

            mVerticalModel.setTitle("Title " + i);

            ArrayList<HorizontalModel> arrayList = new ArrayList<>();

            for (int j = 0; j <= 5; j++) {
                HorizontalModel mHorizontalModel = new HorizontalModel();
                mHorizontalModel.setDescription("Description : " + j);
                mHorizontalModel.setName("Name : " + j);
                arrayList.add(mHorizontalModel);
            }

            mVerticalModel.setArrayList(arrayList);

            mArrayList.add(mVerticalModel);

        }
        mAdapter.notifyDataSetChanged();
    }

}
`
The Error in the Logcat is:
07-15 17:51:26.380 18467-18467/com.example.rachmani.mythematix_linears E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                         Process: com.example.rachmani.mythematix_linears, PID: 18467
                                                                                         java.lang.NullPointerException: Attempt to invoke virtual method 'void com.example.rachmani.mythematix_linears.adapters.VerticalRecyclerViewAdapter.notifyDataSetChanged()' on a null object reference
                                                                                             at com.example.rachmani.mythematix_linears.Fragments.FragmentPractice.setDataOnVerticalRecyclerView(FragmentPractice.java:135)
                                                                                             at com.example.rachmani.mythematix_linears.Fragments.FragmentPractice.onCreate(FragmentPractice.java:87)
                                                                                             at android.support.v4.app.Fragment.performCreate(Fragment.java:2339)
                                                                                             at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1377)
                                                                                             at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1109)
                                                                                             at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:996)
                                                                                             at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:99)
                                                                                             at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2364)
                                                                                             at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
                                                                                             at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2199)
                                                                                             at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:651)
                                                                                             at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:145)
                                                                                             at android.support.v4.view.ViewPager.populate(ViewPager.java:1236)
                                                                                             at android.support.v4.view.ViewPager.populate(ViewPager.java:1084)
                                                                                             at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1614)
                                                                                             at android.view.View.measure(View.java:18035)
                                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5702)
                                                                                             at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1692)
                                                                                             at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1244)
                                                                                             at android.widget.LinearLayout.onMeasure(LinearLayout.java:631)
                                                                                             at android.view.View.measure(View.java:18035)
                                                                                             at android.widget.LinearLayout.measureVertical(LinearLayout.java:963)
                                                                                             at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
                                                                                             at android.view.View.measure(View.java:18035)
                                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5702)
                                                                                             at android.widget.FrameLayout.onMeasure(FrameLayout.java:465)
                                                                                             at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                                             at android.view.View.measure(View.java:18035)
                                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5702)
                                                                                             at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1692)
                                                                                             at android.widget.LinearLayout.measureVertical(LinearLayout.java:760)
                                                                                             at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
                                                                                             at android.view.View.measure(View.java:18035)
                                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5702)
                                                                                             at android.widget.FrameLayout.onMeasure(FrameLayout.java:465)
                                                                                             at android.view.View.measure(View.java:18035)
                                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5702)
                                                                                             at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1692)
                                                                                             at android.widget.LinearLayout.measureVertical(LinearLayout.java:760)
                                                                                             at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
                                                                                             at android.view.View.measure(View.java:18035)
                                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5702)
                                                                                             at android.widget.FrameLayout.onMeasure(FrameLayout.java:465)
                                                                                             at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2785)
                                                                                             at android.view.View.measure(View.java:18035)
                                                                                             at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2461)
                                                                                             at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1445)
                                                                                             at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1680)
                                                                                             at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1323)
                                                                                             at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6686)
                                                                                             at android.view.Choreographer$CallbackRecord.run(Choreographer.java:800)
                                                                                         	at android.view.Choreog

Can you please advice.

**Comment by malikmotani** [comment]
You are binding your view with the butterknife and also trying to register your view components manually. Please remove one of these and no need to put the toolbar in fragment it should be managed from the activity.

**Comment by nuny3010** [comment]
Hi Maddy
Thanks very much for your answer and patience.
I'm just a beginner programmer so it's not always clear to me what the implications of what I'm doing or supposed to do.
Regarding the toolbar ... I assume in also need to remove it from the XML? Is there any other place?
 In addition, I get an error related to  " VerticalRecyclerViewAdapter.notifyDataSetChanged()' on a null object reference"
I am still messing something, can we discuss  it trough privet platform ? at the end of the road we could present the result here...

**Comment by malikmotani** [comment]
For sure add me on skype : malikmotani
